"""initial schema

Revision ID: 197414cd40e5
Revises: 
Create Date: 2026-07-26 00:30:04.496849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197414cd40e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_slug'), 'diseases', ['slug'], unique=True)
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_slug'), 'hospitals', ['slug'], unique=True)
    op.create_table('journey_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('WELCOME', 'GENERAL_EDUCATION', 'DEPARTMENT_INTRO', 'ADMISSION', 'BEFORE_PROCEDURE', 'PROCEDURE', 'AFTER_PROCEDURE', 'DAILY_INPATIENT', 'DISCHARGE', 'HOME_CARE', 'FOLLOW_UP', 'LONG_TERM_MONITORING', name='journeystagecode'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_stages_code'), 'journey_stages', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('SUPER_ADMIN', 'HOSPITAL_ADMIN', 'DEPARTMENT_ADMIN', 'DOCTOR', 'CONTENT_MANAGER', name='rolecode'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_hospital_id'), 'departments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=False)
    op.create_table('treatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatments_disease_id'), 'treatments', ['disease_id'], unique=False)
    op.create_index(op.f('ix_treatments_slug'), 'treatments', ['slug'], unique=False)
    op.create_table('admin_role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_role_assignments_admin_user_id'), 'admin_role_assignments', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_role_assignments_department_id'), 'admin_role_assignments', ['department_id'], unique=False)
    op.create_index(op.f('ix_admin_role_assignments_hospital_id'), 'admin_role_assignments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_admin_role_assignments_role_id'), 'admin_role_assignments', ['role_id'], unique=False)
    op.create_table('education_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_stage_id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_stage_id'], ['journey_stages.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_sections_journey_stage_id'), 'education_sections', ['journey_stage_id'], unique=False)
    op.create_index(op.f('ix_education_sections_treatment_id'), 'education_sections', ['treatment_id'], unique=False)
    op.create_table('qr_access_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='qraccesspointstatus'), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_access_points_access_token'), 'qr_access_points', ['access_token'], unique=True)
    op.create_index(op.f('ix_qr_access_points_department_id'), 'qr_access_points', ['department_id'], unique=False)
    op.create_index(op.f('ix_qr_access_points_hospital_id'), 'qr_access_points', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_qr_access_points_status'), 'qr_access_points', ['status'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body_richtext', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['education_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_section_id'), 'lessons', ['section_id'], unique=False)
    op.create_table('patient_access_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_access_point_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_access_point_id'], ['qr_access_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_access_profiles_qr_access_point_id'), 'patient_access_profiles', ['qr_access_point_id'], unique=False)
    op.create_table('content_targeting_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('disease_id', sa.UUID(), nullable=True),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_targeting_rules_department_id'), 'content_targeting_rules', ['department_id'], unique=False)
    op.create_index(op.f('ix_content_targeting_rules_disease_id'), 'content_targeting_rules', ['disease_id'], unique=False)
    op.create_index(op.f('ix_content_targeting_rules_hospital_id'), 'content_targeting_rules', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_content_targeting_rules_lesson_id'), 'content_targeting_rules', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_content_targeting_rules_treatment_id'), 'content_targeting_rules', ['treatment_id'], unique=False)
    op.create_table('favorite_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_access_profile_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['patient_access_profile_id'], ['patient_access_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_records_lesson_id'), 'favorite_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_favorite_records_patient_access_profile_id'), 'favorite_records', ['patient_access_profile_id'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_access_profile_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['patient_access_profile_id'], ['patient_access_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_records_lesson_id'), 'feedback_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_patient_access_profile_id'), 'feedback_records', ['patient_access_profile_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'IMAGE', 'PDF', 'ANIMATION', name='mediatype'), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_lesson_id'), 'media_assets', ['lesson_id'], unique=False)
    op.create_table('patient_journey_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_access_profile_id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=True),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('has_surgery', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('current_stage', sa.Enum('WELCOME', 'GENERAL_EDUCATION', 'DEPARTMENT_INTRO', 'ADMISSION', 'BEFORE_PROCEDURE', 'PROCEDURE', 'AFTER_PROCEDURE', 'DAILY_INPATIENT', 'DISCHARGE', 'HOME_CARE', 'FOLLOW_UP', 'LONG_TERM_MONITORING', name='journeystagecode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['patient_access_profile_id'], ['patient_access_profiles.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_journey_profiles_disease_id'), 'patient_journey_profiles', ['disease_id'], unique=False)
    op.create_index(op.f('ix_patient_journey_profiles_patient_access_profile_id'), 'patient_journey_profiles', ['patient_access_profile_id'], unique=False)
    op.create_index(op.f('ix_patient_journey_profiles_treatment_id'), 'patient_journey_profiles', ['treatment_id'], unique=False)
    op.create_table('progress_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_access_profile_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='lessonprogressstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['patient_access_profile_id'], ['patient_access_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_lesson_id'), 'progress_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_progress_records_patient_access_profile_id'), 'progress_records', ['patient_access_profile_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_lesson_id'), 'quiz_questions', ['lesson_id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_options_question_id'), 'quiz_options', ['question_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_access_profile_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_access_profile_id'], ['patient_access_profiles.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_patient_access_profile_id'), 'quiz_attempts', ['patient_access_profile_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_patient_access_profile_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_options_question_id'), table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_quiz_questions_lesson_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_progress_records_patient_access_profile_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_lesson_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_patient_journey_profiles_treatment_id'), table_name='patient_journey_profiles')
    op.drop_index(op.f('ix_patient_journey_profiles_patient_access_profile_id'), table_name='patient_journey_profiles')
    op.drop_index(op.f('ix_patient_journey_profiles_disease_id'), table_name='patient_journey_profiles')
    op.drop_table('patient_journey_profiles')
    op.drop_index(op.f('ix_media_assets_lesson_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_feedback_records_patient_access_profile_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_lesson_id'), table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_favorite_records_patient_access_profile_id'), table_name='favorite_records')
    op.drop_index(op.f('ix_favorite_records_lesson_id'), table_name='favorite_records')
    op.drop_table('favorite_records')
    op.drop_index(op.f('ix_content_targeting_rules_treatment_id'), table_name='content_targeting_rules')
    op.drop_index(op.f('ix_content_targeting_rules_lesson_id'), table_name='content_targeting_rules')
    op.drop_index(op.f('ix_content_targeting_rules_hospital_id'), table_name='content_targeting_rules')
    op.drop_index(op.f('ix_content_targeting_rules_disease_id'), table_name='content_targeting_rules')
    op.drop_index(op.f('ix_content_targeting_rules_department_id'), table_name='content_targeting_rules')
    op.drop_table('content_targeting_rules')
    op.drop_index(op.f('ix_patient_access_profiles_qr_access_point_id'), table_name='patient_access_profiles')
    op.drop_table('patient_access_profiles')
    op.drop_index(op.f('ix_lessons_section_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_qr_access_points_status'), table_name='qr_access_points')
    op.drop_index(op.f('ix_qr_access_points_hospital_id'), table_name='qr_access_points')
    op.drop_index(op.f('ix_qr_access_points_department_id'), table_name='qr_access_points')
    op.drop_index(op.f('ix_qr_access_points_access_token'), table_name='qr_access_points')
    op.drop_table('qr_access_points')
    op.drop_index(op.f('ix_education_sections_treatment_id'), table_name='education_sections')
    op.drop_index(op.f('ix_education_sections_journey_stage_id'), table_name='education_sections')
    op.drop_table('education_sections')
    op.drop_index(op.f('ix_admin_role_assignments_role_id'), table_name='admin_role_assignments')
    op.drop_index(op.f('ix_admin_role_assignments_hospital_id'), table_name='admin_role_assignments')
    op.drop_index(op.f('ix_admin_role_assignments_department_id'), table_name='admin_role_assignments')
    op.drop_index(op.f('ix_admin_role_assignments_admin_user_id'), table_name='admin_role_assignments')
    op.drop_table('admin_role_assignments')
    op.drop_index(op.f('ix_treatments_slug'), table_name='treatments')
    op.drop_index(op.f('ix_treatments_disease_id'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_index(op.f('ix_departments_hospital_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_journey_stages_code'), table_name='journey_stages')
    op.drop_table('journey_stages')
    op.drop_index(op.f('ix_hospitals_slug'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_diseases_slug'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
